#!/usr/bin/python
# -*- coding: utf-8 -*-

from datetime import datetime


# d_last = datetime(year=2015, month=5, day=10, hour=2)
# d_last = datetime(year=2015, month=8, day=9, hour=3)
# d_last = datetime(year=2015, month=10, day=2, hour=17)
# d_last = datetime(year=2015, month=12, day=28, hour=1)
# d_last = datetime(year=2016, month=1, day=31, hour=0)
d_last = datetime(year=2016, month=2, day=7, hour=0)

d_now = datetime.now()

delta = d_now - d_last

seconds = float(delta.total_seconds())
minutes = seconds / 60.0

package_price = 6.0
package_amount = 22.0
price_per_cigarette = package_price / package_amount
cigarettes_per_day = 18.0
cigarettes_per_hour = cigarettes_per_day / 24
cigarettes_per_minute = cigarettes_per_hour / 60

minute_price = cigarettes_per_minute * price_per_cigarette
euros = minutes * minute_price
cigarettes = minutes * cigarettes_per_minute

print d_last.strftime("last cigarette: %A, %d. %B %Y %H:%S")
print "smoke-free since %s" % delta
print "%10.2f € saved" % euros
print "%i cigarettes saved" % cigarettes
