#!/usr/bin/python
# -*- coding: utf-8 -*-

from datetime import datetime


# d_last = datetime(year=2016, month=5, day=27, hour=1)
# d_last = datetime(year=2016, month=7, day=24, hour=2)
# d_last = datetime(year=2016, month=9, day=27, hour=23)
d_last = datetime(year=2016, month=10, day=23, hour=3)

d_now = datetime.now()
delta = d_now - d_last
seconds = float(delta.total_seconds())
minutes = seconds / 60.0

package_price = 6.0
package_amount = 22.0
price_per_cigarette = package_price / package_amount
cigarettes_per_day = 18.0
cigarettes_per_hour = cigarettes_per_day / 24
cigarettes_per_minute = cigarettes_per_hour / 60

minute_price = cigarettes_per_minute * price_per_cigarette
euros = minutes * minute_price
cigarettes = minutes * cigarettes_per_minute
smoke_time = cigarettes * 5 / 60

rem = int(cigarettes)
i = 1
while rem > 0:
    if rem > int(cigarettes_per_day):
        print "day %5s " % i + "🚬 " * int(cigarettes_per_day)
        rem = rem - int(cigarettes_per_day)
    else:
        print "day %5s " % i + "🚬 " * rem
        rem = 0
    i = i + 1

print "\nlast cigarette:"
print d_last.strftime("📅  %A, %d. %B %Y %H:%S")
print "⌛  %s" % delta
print "💰  %0.2f € saved" % euros
print "🚬  %i cigarettes saved" % cigarettes
print "🕒  %0.2f hours gained" % smoke_time
